### ISSUE TITLE
Error while using the Tool

### ISSUE THREAD

**Issue by theinfosecguy** [D4Vinci/Clickjacking-Tester#4]
[+] Website is vulnerable!
Traceback (most recent call last):
  File "Clickjacking_Tester.py", line 58, in <module>
    if __name__ == '__main__': main()
  File "Clickjacking_Tester.py", line 52, in main
    create_poc(site.split('\n')[0])
  File "Clickjacking_Tester.py", line 35, in create_poc
    with open(url + ".html", "w") as f:
FileNotFoundError: [Errno 2] No such file or directory: ----

**Comment by SkyNpEH** [comment]
check my comment on this
